name: 'Hello world workflow'

# To check for all branches use on : push, it can be check for any action like pull push etc

on:
  push:
    branches:
      - main
      - dummyBr

jobs: 
  
  hello_world: # job 1
    runs-on: ubuntu-latest
    steps:
      - name: 'Print hello world'
        run: echo 'Hello world this is my first ci cd job using github actions'